program: main.py
method: grid  # Change to 'random' or 'bayes' if needed
project: DDS_MoG_5d_10_modes exploration
name: MoS, rKL, off_policy, sigma_init=1, T_start scan 
command:
  - ${env}
  - python
  - ${program}
  - ${args}
  - --use_interpol_gradient
  - --use_normal
  - --use_off_policy
  - --gridsearch
parameters:
  SDE_Loss:
    values: ['Bridge_rKL_logderiv']   #,'Bridge_LogVarLoss'
  Energy_Config:
    value: GMMDistraxEasy
  n_integration_steps:
    value: 128
  T_start:
    values: [60, 80]
  T_end:
    value: 1.0
  batch_size:
    value: 2000
  lr:
    value: 0.005
  Energy_lr:
    value: 0.0
  SDE_lr:
    value: 0.005
  Interpol_lr:
    value: 0.0
  N_anneal:
    value: 4000
  feature_dim:
    value: 128
  n_hidden:
    value: 128
  GPU:
    value: -1
  beta_max:
    values: [0.1, 0.5, 1]
  beta_min:
    value: 0.01
  Network_Type:
    value: FeedForward
  SDE_Type:
    value: Bridge_SDE
  repulsion_strength:
    value: 0.0
  sigma_init:
    values: [1.0]
  model_seed:
    value: 0
  n_particles:
    value: 5
  epochs_per_eval:
    value: 50