wandb_version: 1

dim_x:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
num_epochs:
  desc: null
  value: 100
steps_per_epoch:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727186719
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.10.11
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
