wandb_version: 1

EnergyConfig:
  desc: null
  value:
    name: GaussianMixture
    dim_x: 1
    means:
    - -5.0
    - 5.0
    variances:
    - 1.0
    - 1.0
    weights:
    - 0.5
    - 0.5
Anneal_Config:
  desc: null
  value:
    name: Linear
    T_start: 0.4
    T_end: 0.0
    N_anneal: 1000
SDE_Loss_Config:
  desc: null
  value:
    name: Reverse_KL_Loss
    SDE_Type_Config:
      name: VP_SDE
      beta_min: 0.1
      beta_max: 10.0
lr:
  desc: null
  value: 0.001
n_hidden:
  desc: null
  value: 64
n_layers:
  desc: null
  value: 3
num_epochs:
  desc: null
  value: 1000
steps_per_epoch:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 100
n_integration_steps:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728035504
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
